version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm start

  # 后端服务
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_PATH=/app/database/tasks.db
    volumes:
      - ../backend:/app
      - ../database:/app/database
      - /app/node_modules
    command: npm run dev

  # 数据库服务（可选，如果使用外部数据库）
  # database:
  #   image: sqlite:latest
  #   volumes:
  #     - ../database:/data

volumes:
  node_modules_frontend:
  node_modules_backend:

networks:
  default:
    name: task-manager-network